version: '3'
services:

  web:
    build: .
    environment:
      DB_HOST: db:3306
      DB_USER: root
      DB_PASSWD: janejane123456
      DB_NAME: tiebacloud
      CSRF: "false"
    ports:
      - "80:8080"
    links:
      - db
    depends_on:
      - db

  db:
    image: "mysql:5.5"
    environment:
      MYSQL_DATABASE: tiebacloud
      MYSQL_ROOT_PASSWORD: janejane123456
